### ISSUE TITLE
Adding type dictionary?

### ISSUE THREAD

**Issue by ouvrierl** [populse/populse_db#23]
In MIA, we would need the type dictionary for the pipelines.
For the pipeline history, we need to store the inputs and the outputs in the database (tuples name, value).
Should we add the type dict (I don't know how we could search in it, but we do not need to search in MIA), or I just put string type and store the str representation of the dictionaries?

**Comment by sapetnioc** [comment]
That is a good question. If I understand there would be two features that could be introduced:

1. A new data type `dict` (and eventually `list_dict`) that would only be used to have transparent serialization/deserialization for user. It would basically support a limited set of filter operations (e.g. `=` and `!=`).
1. An extension of the filter syntax to allow filter selection using values inside the dictionary.

I am in favor of both but I think the second point is a bit complex to address. So if we do not have a use case right now, it is probably not a priority.

I have a question about the `dict`type. What kind of dict content would be allowed ? One possible answer would be to restrict to JSON content. This would follow a standard and allow to add filtering possibilities in Postgresql (since it has a JSON column type with corresponding SQL extensions). We would also immediately have an implementation of dict serialization into string for SQLite. The major drawback is that dates and time are not compatible with JSON (David has worked on that). If we choose to support dates and time, the deserialization of documents with dictionaries could be slow (necessary to parse recursively all dict items to check if there are dates to deserialize).

If we finally choose to restrict dict to JSON content, the new data types could be `json` and `list_json`.

**Comment by ouvrierl** [comment]
I am ok with allowing dictionaries containing only JSON content, it should not be a restriction for what we need to store in MIA
